# Site
name: 'TopAI Free'
description: 'The Top AI free curated list to help you find the best AI applications to boost your productivity in work and life activities. Updated daily with latest AI tools in the market in various categories.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: '/'
disqus: 'TopAIfree'
email: 'topaifree@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Sal
      site:          https://topaifree.github.io/
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of TopAI Free, the website you're currently previewing. I hope you like it!"
      email:          topaifree@gmail.com
      twitter:        https://twitter.com/topaifree

    jane:
      name:           Jane
      site:           https://topaifree.github.io/
      avatar:         assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          topaifree@gmail.com
      twitter:        https://twitter.com/topaifree
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]